version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      DATABASE_URL: ${DATABASE_URL}

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    environment:
      DATABASE_URL: ${DATABASE_URL}